#!/usr/bin/env bash

# TODO rewrite this shit
bat() {	
	bat=`cat /sys/class/power_supply/BAT0/capacity`
	if [ `cat /sys/class/power_supply/BAT0/status` == Charging ]; then bat="+${bat}" ; fi
	echo -e "BAT:${bat}%"
}

ram() {
	#mem=`free | awk '/Mem/ {printf "%dM/%dM (%d%)\n", $3/1024.0, $2/1024.0, $3/$2*100 }'`
	ram=`free | awk '/Mem/ {printf "%d%", $3/$2*100.0  }'`
	echo -e "RAM:$ram"
}

pkg() {
	pkg=`xbps-query -l | wc -l`
	echo -e "PKG:$pkg"
}

vol() {
	vol=`df -h | awk '/mmcblk1p3/  {print $5}'`
	echo -e "VOL:$vol"
}
snd() {
	snd=`amixer sget Master | awk '/Mono/ {printf "%s%s",  $4, $6}'`
	echo -e "SND:$snd"
}


SLEEP_SEC=3

while :; do
	echo "$(bat) | $(ram) | $(vol) | $(pkg) | $(snd)"
	sleep $SLEEP_SEC
done
