#!/usr/bin/env bash

# TODO rewrite this shit
bat() {	
	bat=`cat /sys/class/power_supply/BAT0/capacity`
	if [ `cat /sys/class/power_supply/BAT0/status` == Charging ]; then bat="+${bat}" ; fi
	echo -e "BAT:${bat}%"
}

mem() {
	#mem=`free | awk '/Mem/ {printf "%dM/%dM (%d%)\n", $3/1024.0, $2/1024.0, $3/$2*100 }'`
	mem=`free | awk '/Mem/ {printf "%d%", $3/$2*100.0  }'`
	echo -e "MEM:$mem"
}

pcg() {
	pcg=`xbps-query -l | wc -l`
	echo -e "PCG:$pcg"
}

vol() {
	vol=`df -h | awk '/mmcblk1p3/  {print $5}'`
	echo -e "VOL:$vol"
}
snd() {
	snd=`amixer sget Master | awk '/Mono/ {printf "%s%s",  $4, $6}'`
	echo -e "$snd"
}


SLEEP_SEC=3

while :; do
	echo "$(bat) | $(mem) | $(vol) | $(pcg)  $(snd) "
	sleep $SLEEP_SEC
done
