#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

my_laptop_external_monitor=$(xrandr --query | grep 'HDMI1')
if [[ $my_laptop_external_monitor = *connected* ]]; then
    xrandr --output HDMI1 --primary --mode 1920x1080 --rotate normal --output eDP1 --off
    xrandr --output HDMI1 --rotate right
fi

bspc config remove_disabled_monitors true
bspc config remove_unplugged_monitors true
bspc config merge_overlapping_monitors false

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         2
bspc config window_gap          14


bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer true
bspc config pointer_follows_focus true

bspc rule -a firefox desktop='^2'
bspc rule -a TelegramDesktop desktop='^3'
bspc rule -a Thunderbird desktop='^4'

bspc rule -a zoom state=floating


#bspc rule -a Gimp desktop='^8' state=floating follow=on
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off

. "${HOME}/.cache/wal/colors.sh"

bspc config normal_border_color "$color2"
bspc config active_border_color "$color1"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color15"
